name: Build

on:
  push:
    branches: [main]
    paths:
      - src/**
      - .github/workflows/main.yml
      - package.json
      - tsconfig.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: yarn

      - name: Install node dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn turbo lint

      - name: Build
        run: yarn turbo build
